// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.upsam.roo.quizzusers.domain;

import com.upsam.roo.quizzusers.domain.UsuarioIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UsuarioIntegrationTest_Roo_Configurable {
    
    declare @type: UsuarioIntegrationTest: @Configurable;
    
}
